version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - "6379:6379"